services:
  - type: web
    name: Manyoo_Rails_Task
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_MASTER_KEY
        sync: false
    
